#Build Stage
FROM maven:3.8.6-openjdk-18-slim AS MAVEN_BUILD
COPY pom.xml /app/
COPY src /app/src
WORKDIR /app/
RUN mvn package

# Run Stage
From openjdk:18
WORKDIR /app
COPY --from=MAVEN_BUILD /app/target/backendbirthday-1.0-SNAPSHOT-jar-with-dependencies.jar /app/
COPY src/main/resources/input.json /app/
ENTRYPOINT ["java","-jar","backendbirthday-1.0-SNAPSHOT-jar-with-dependencies.jar", "/input.json"]